version: 0.1

phases:
  install:
    commands:
      - apk add --no-cache \
        py-pip=9.0.0-r1
        pip install \
        docker-compose==1.12.0
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker-compose build
      - docker-compose up -d
      - sleep 15s
      - docker-compose exec -T server php composer.phar install -n
      - docker-compose exec -T server bin/phpunit -c app