version: 0.1
phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
# ECRへのログインを行う場合は環境設定と合わせて実行する。
#      - echo Logging in to Amazon ECR
#      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
# container作成
      - docker-compose build
# container起動
      - docker-compose up -d
      - sleep 15s
      - docker ps
# container内のcomposer実行
      - docker-compose exec -T apache php composer.phar install -n
# test実行
      - docker-compose exec -T apache bin/phpunit -c app